/*  =========================================================================
    agent-outage - generated layer of public API

    Copyright (C) 2014 - 2015 Eaton

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef AGENT_OUTAGE_LIBRARY_H_INCLUDED
#define AGENT_OUTAGE_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <malamute.h>
#include <biosproto.h>

//  AGENT_OUTAGE version macros for compile-time API detection
#define AGENT_OUTAGE_VERSION_MAJOR 0
#define AGENT_OUTAGE_VERSION_MINOR 1
#define AGENT_OUTAGE_VERSION_PATCH 0

#define AGENT_OUTAGE_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define AGENT_OUTAGE_VERSION \
    AGENT_OUTAGE_MAKE_VERSION(AGENT_OUTAGE_VERSION_MAJOR, AGENT_OUTAGE_VERSION_MINOR, AGENT_OUTAGE_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined AGENT_OUTAGE_STATIC
#       define AGENT_OUTAGE_EXPORT
#   elif defined AGENT_OUTAGE_EXPORTS
#       define AGENT_OUTAGE_EXPORT __declspec(dllexport)
#   else
#       define AGENT_OUTAGE_EXPORT __declspec(dllimport)
#   endif
#else
#   define AGENT_OUTAGE_EXPORT
#endif

//  Project has no stable classes, so we build the draft API
#undef  AGENT_OUTAGE_BUILD_DRAFT_API
#define AGENT_OUTAGE_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef AGENT_OUTAGE_BUILD_DRAFT_API
typedef struct _bios_outage_server_t bios_outage_server_t;
#define BIOS_OUTAGE_SERVER_T_DEFINED
#endif // AGENT_OUTAGE_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef AGENT_OUTAGE_BUILD_DRAFT_API
#include "bios_outage_server.h"
#endif // AGENT_OUTAGE_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
